name: Build Flutter Web

on:
  push:
    branches:
      - main  # یا هر برنچ دیگری که می‌خواهید

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # نسخه جاوا مورد نیاز
        distribution: 'adopt'  # توزیع جاوا

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.0'  # نسخه فلاتر به‌روزرسانی شده

    - name: Get dependencies
      run: flutter pub get

    - name: Build web
      run: flutter build web --release

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web
        user_name: 'Milad-heydarloo'  # نام کاربری شما در GitHub
        user_email: 'phone.sync.heydarloo@gmail.com'  # ایمیل شما در GitHub
