name: Build Flutter Windows

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.0'

    - name: Get dependencies
      run: flutter pub get

    - name: Clean build
      run: flutter clean

    - name: Build Windows
      run: flutter build windows --release

    - name: Create output directory
      run: mkdir .\my-output-folder

    - name: Move build files
      run: |
        move .\build\windows\runner\Release\* .\my-output-folder\

    - name: List files in output directory
      run: dir .\my-output-folder

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      with:
        upload_artifacts: true
        files: my-output-folder/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
